# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='\u0438\u043c\u044f')),
                ('description', models.TextField(blank=True, verbose_name='\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
            ],
        ),
    ]
