# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u0438\u043c\u044f \u043f\u0440\u043e\u0434\u0443\u043a\u0442\u0430')),
                ('image', models.ImageField(blank=True, upload_to='products_images')),
                ('short_desc', models.CharField(blank=True, max_length=60, verbose_name='\u043a\u0440\u0430\u0442\u043a\u043e')),
                ('description', models.TextField(blank=True, verbose_name='\u043f\u043e\u0434\u0440\u043e\u0431\u043d\u043e')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='\u0446\u0435\u043d\u0430')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='\u0441\u043a\u043b\u0430\u0434')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.ProductCategory')),
            ],
        ),
    ]
